name: CICD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run composer install
        run: composer install -n --prefer-dist
      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
